aws에서 security group 정보 가져오는 API
ECTwo/ec2-backend pull request #2
Opened 2020-10-02 15:11 UTC by KimKiHyuk

Closes: #1 

예제 코드입니다.

2020-10-02 15:25 UTC, nnnlog requested changes

2020-10-02 15:25 UTC, nnnlog commented on src/routes/v1/Aws.ts
> +    --rm aws ec2 describe-security-groups \
커맨드 쉘 실행에서 값 검증 없이 그냥 넣으면 injection이 가능할 것 같습니다.

2020-10-02 15:43 UTC, KimKiHyuk commented on src/routes/v1/Aws.ts
> +    --rm aws ec2 describe-security-groups \
백엔드 프론트엔드가 같은 CORS를 적용해서 프론트쪽에서 믿을 수 있는 입력값을 보내는 경우도 injection 가능성이 있나요??  

그리고 혹시 공격예시 알려주실 수 있을까요? 
```
execShellCommand(param)
```
param에 인젝션 스트링을 넣어서 공격한다는걸로 이해했는데 맞나요? 
제가 보안을 잘 몰라서 ㅎㅎ..
맞다면 docker 내부에서 모든 명령어가 실행되므로 안전하지 않나요?

2020-10-02 23:53 UTC, nnnlog commented on src/routes/v1/Aws.ts
> +    const { region, access_key, secret_key } = req.body;
#1 에 보면 GET 요청으로 보낸다고 하는데 요렇게 하면 POST body를 가져오는거 아니에요?

2020-10-03 00:05 UTC, nnnlog commented on src/routes/v1/Aws.ts
> +    --rm aws ec2 describe-security-groups \
![image](https://user-images.githubusercontent.com/20399222/94978150-0343ca00-0557-11eb-8222-019e794fa3a5.png)

![image](https://user-images.githubusercontent.com/20399222/94978216-5e75bc80-0557-11eb-980d-051e91b954cf.png)


인자를 그대로 넣었기 때문에 `||` 로 도커의 커맨드를 자르고, 원하는 커맨드를 넣어 실행할 수 있을 것 같아요. (뒤에 남은 도커 인자들은 /dev/null로 보내서 자를 수 있고)
CORS와는 상관없이 지금은 저희만 사용하지만, 로그인/회원가입을 넣으면 로그인한 사용자는 저 요청을 다 날릴 수 있을 것 같아요

2020-10-03 03:46 UTC, KimKiHyuk commented on src/routes/v1/Aws.ts
> +    const { region, access_key, secret_key } = req.body;
앗 header로 한줄 알았는데 body였네요 ㅋㅋ;

header로 변경하겠습니다

2020-10-03 04:00 UTC, KimKiHyuk commented on src/routes/v1/Aws.ts
> +    --rm aws ec2 describe-security-groups \
이해했습니다 설명 감사합니다 👍 

regex로 영문, 숫자, - 를 제외한 문자들이 오면 커맨드 실행 안하고 400 리턴 해주려고 하는데 효과가 있는 방법일까요?

2020-10-03 04:09 UTC, KimKiHyuk commented on src/routes/v1/Aws.ts
> +    const { region, access_key, secret_key } = req.body;
추가로 region은 header 말고 query에 담는걸로 변경했습니다

2020-10-03 04:12 UTC, nnnlog commented on src/routes/v1/Aws.ts
> +    --rm aws ec2 describe-security-groups \
regex로 거르고 400 Bad Request 반환해주면 좋을 것 같아요
저 access key들이 다른 API에서 공통으로 사용된다면 미들웨어로 api 라우터에 가기 전에 앞단에서 거르는게 제일 좋을 것 같아요

2020-10-03 04:15 UTC, KimKiHyuk commented on src/routes/v1/Aws.ts
> +    --rm aws ec2 describe-security-groups \
네 좋은 생각이십니다. 
일단 테스트 단계에서 access_key들은 거의 공통으로 사용될테니 미들웨어 걸어서 regex로 체크하는 방법으로 변경하겠습니다 :)

2020-10-12 04:58 UTC, merged

2020-10-12 05:01 UTC, KimKiHyuk commented
앗.. 이 브랜치 커밋이 필요해서 다른쪽에서 머지 후 다른 브랜치에서 master로 머지했는데 여기껏도 루트 베이스가 정확히 일치해서 자동 머지된 것 같네요.. ㅠㅠ 찬솔님이 언급하신 이슈는 따로 분리해두겠습니다.